<?php

/**
 * @file
 * Install and uninstall functions for the Tin Can API (iMinds) module.
 */

/**
 * Implements hook_install().
 */
function tincanapi_profile_install() {

  // Send initial data of the users already to the LRS.
  _tincanapi_profile_sync_all();

}

/**
 * Add profile pictures to all users.
 */
function tincanapi_profile_update_7101() {

  // Send initial data of the users already to the LRS.
  _tincanapi_profile_sync_all();

}
