<?php

/**
 * @file
 * A Tin Can API module to handle profile specific tracking.
 */

use Drupal\tincanapi\Utilities\Utilities;


/**
 * Implements hook_user_insert().
 */

function tincanapi_profile_user_insert(\Drupal\user\UserInterface $account) {
  _tincanapi_profile_trigger_update($account);
}

/**
 * Implements hook_user_update().
 */

function tincanapi_profile_user_update(\Drupal\user\UserInterface $account) {
  _tincanapi_profile_trigger_update($account);
}

/**
 * Creates the profile document and send it to LRS.
 *
 * @param object $account
 *   The Drupal user account.
 */
function _tincanapi_profile_trigger_update(\Drupal\user\UserInterface $account) {
  $profile = array();
  $profile['avatar'] = NULL;
  
  $options = ['absolute' => TRUE];
  $user_profile_url = \Drupal\Core\Url::fromRoute('entity.user.canonical', ['user' => 1], $options);
  $user_profile_url = $user_profile_url->toString();
  $profile['profile'] = $user_profile_url;
  
  /*
  if (variable_get('user_pictures', 0)) {
    if (!empty($account->picture)) {
      if (is_numeric($account->picture)) {
        $account->picture = file_load($account->picture);
      }

      if (!empty($account->picture->uri)) {
        $profile['avatar'] = file_create_url($account->picture->uri);
      }
    }
  }*/

  $profile["roles"] = array();
  foreach ($account->getRoles() as $role) {
    //$role = user_role_load($role);
    //$role = \Drupal::entityTypeManager()->getStorage('user')->load($id);
    //if ($role) {
      //$profile["roles"][] = $role->name;
    //}
    $profile["roles"][] = $role;
  }

  if ($account->id() == 1) {
    $profile["roles"][] = "administrator";
  }

  tincanapi_profile_track($account, $profile);
}

/**
 * Send profile information to LRS.
 *
 * @param object $account
 *   The Drupal user account.
 * @param array $profile
 *   An array of profile info to be added to the statement.
 */
function tincanapi_profile_track(\Drupal\user\UserInterface $account, array $profile) {
  $data = array();
  $utils = new Utilities();

  $data['agent'] = $utils->tincanapi_get_actor($account);
  $data['agent']['objectType'] = 'Agent';
  $data['agent'] = json_encode($data['agent']);
  $data['profileId'] = 'userProfile';
  $data['content'] = json_encode($profile);
  $utils->tincanapi_send('agents/profile', 'POST', $data);
}

/**
 * Sync all already created profiles.
 */
function _tincanapi_profile_sync_all() {
  if (\Drupal::moduleHandler()->moduleExists('tincanapi')) {
    $users = \Drupal::entityManager()->getStorage('user');
    $user_names = array();

    foreach ($users as $user) {
      if ($user->status) {
        _tincanapi_profile_trigger_update($user);
      }
    }
  }
}
